defaults:
  - _self_
  - env: cartpole
  - alg: shac

hydra:
  sweep:
    dir: ${env:HOME}/checkpoints/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${wandb.sweep_name_prefix}-${hydra.job.num}

exp_name: shac_benchmarks

id: ${hydra.job.id}
resume_model: null

general:
  play: False
  logdir: logs/tmp/shac/
  save_interval: False
  no_time_stamp: False
  render: False
  device: cuda:0
  run_wandb: True
  seed: 0
  train: True
  checkpoint:
  multi_gpu: False
  num_envs: 


# env-specific defaults for different algs
env:
  gamma: 0.99
  lambda: 0.95
  player:
    games_num: 12
    num_actors: 4

  shac:
    actor_mlp:
      units:
        - 64
        - 64
    critic_mlp:
      units:
        - 64
        - 64
    target_critic_alpha: 0.2
    actor_lr: 1e-3
    critic_lr: 1e-3
    max_epochs: 2000
    save_interval: 400
    steps_num: 32
    betas: (0.7, 0.95)

wandb:
  project: shac
  group: ${exp_name}
  sweep_name_prefix: ${alg.diff_env.name}_${alg.name}-run
