_target_: shac.algorithms.ahac5.AHAC5
_recursive_: False
actor_config:
  _target_: shac.models.actor.ActorStochasticMLP
  units: ${resolve_child:[64,64],${env.shac.actor_mlp},units}
  activation: elu
critic_config:
  _target_: shac.models.critic.DoubleCriticMLP
  units: ${resolve_child:[64,64],${env.shac.critic_mlp},units}
  activation: elu
actor_lr: ${resolve_child:2e-3,${env.ahac5},actor_lr}
critic_lr: ${resolve_child:2e-3,${env.ahac5},critic_lr}
lambd_lr: ${resolve_child:1e-4,${env.ahac5},lambd_lr}
h_lr: ${resolve_child:1e-2,${env.ahac5},h_lr}
lr_schedule: linear
obs_rms: True
ret_rms: False
critic_iterations: ${resolve_child:null,${env.ahac5},critic_iterations}
critic_batches: 4
critic_method: td-lambda # ('td-lambda', 'one-step')
lam: 0.95
gamma: 0.99
max_epochs: ${resolve_child:2000,${env.ahac5},max_epochs}
steps_min: 8
steps_max: 64
grad_norm: ${resolve_child:1.0,${env.ahac5},grad_norm}
critic_grad_norm: ${resolve_child:1.0,${env.ahac5},critic_grad_norm}
save_interval: ${resolve_child:400,${env.ahac5},save_interval}
stochastic_eval: False
eval_runs: 12
train: ${general.train}
device: ${general.device}
