name: df_hopper
env_name: HopperEnv

config:
  _target_: shac.envs.HopperEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: 1024
  seed: ${general.seed}
  episode_length: 1000
  no_grad: ??? # decided based on algorithm
  stochastic_init: True
  MM_caching_frequency: 4
  early_termination: True
  contact_ke: 2e4
  contact_kd:

shac:
  actor_lr: 2e-3
  critic_lr: 4e-3
  max_epochs: 500
  actor_mlp:
    units: [128, 64, 32]
  critic_mlp:
    units: [64, 64]
  save_interval: 100

ahac:
  actor_lr: 2e-3
  critic_lr: 4e-3
  max_epochs: 500
  # jacobian_norm: 1.0
  # grad_norm: null
  actor_mlp:
    units: [128, 64, 32]
  critic_mlp:
    units: [64, 64]
  save_interval: 100

ahac5:
  actor_lr: 2e-3
  critic_lr: 4e-3
  h_lr: 1e-2
  max_epochs: 500
  actor_mlp:
    units: [128, 64, 32]
  critic_mlp:
    units: [64, 64]
  save_interval: 100


ppo:
  max_epochs: 200
  minibatch_size: 8192
  num_actors: 1024
  horizon_length: 240
  save_frequency: 50
  save_best_after: 50
  actor_mlp:
    units: [128, 64, 32]
  critic_mlp:
    units: [64, 64]

svg:
  num_train_steps: 10000000
  replay_buffer_capacity: 1000000
