name: df_snuhumanoid
env_name: SNUHumanoidEnv

config:
  _target_: shac.envs.SNUHumanoidEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: 64
  no_grad: ??? # decided based on algorithm
  stochastic_init: True
  seed: ${general.seed}
  episode_length: 1000
  MM_caching_frequency: 8

shac:
  actor_lr: 2e-3
  critic_lr: 5e-4
  max_epochs: 5000
  target_critic_alpha: 0.995
  actor_mlp:
    units: [512, 256]
  critic_mlp:
    units: [256, 256]

ahac:
  actor_lr: 2e-3
  critic_lr: 5e-4
  max_epochs: 5000
  # jacobian_norm: 1.0
  # grad_norm: null
  actor_mlp:
    units: [512, 256]
  critic_mlp:
    units: [256, 256]

ahac5:
  actor_lr: 2e-3
  critic_lr: 5e-4
  h_lr: 5e-4
  max_epochs: 5000
  grad_norm: 0.5
  critic_grad_norm: 1.0  
  actor_mlp:
    units: [512, 256]
  critic_mlp:
    units: [256, 256]

ppo:
  max_epochs: 50000
  minibatch_size: 8192
  num_actors: 1024
  horizon_length: 32
  save_frequency: 500
  save_best_after: 500
  actor_mlp:
    units: [256, 128, 64]
  critic_mlp:
    units: [256, 128, 64]
